# Generated by Django 3.1.5 on 2021-01-05 21:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_first_name', models.CharField(max_length=100)),
                ('doctor_last_name', models.CharField(max_length=100)),
                ('doctor_data_json', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_data_json', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
