# Generated by Django 3.1.5 on 2021-01-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_webapp', '0002_auto_20210108_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorinformation',
            old_name='data_json',
            new_name='doctor_data_json',
        ),
        migrations.RenameField(
            model_name='doctorinformation',
            old_name='first_name',
            new_name='doctor_first_name',
        ),
        migrations.RenameField(
            model_name='doctorinformation',
            old_name='last_name',
            new_name='doctor_last_name',
        ),
    ]
