# Generated by Django 3.1.5 on 2021-01-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_webapp', '0005_auto_20210118_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drchrono_webapp.doctorinformation'),
        ),
    ]
