# Generated by Django 3.1.5 on 2021-01-19 18:33

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_webapp', '0006_patientinformation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='doctor',
            field=models.ForeignKey(default=jsonfield.fields.JSONField(default={}), on_delete=django.db.models.deletion.CASCADE, to='drchrono_webapp.doctorinformation'),
        ),
    ]
