# Generated by Django 3.1.5 on 2021-01-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_webapp', '0003_auto_20210108_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='patientinformation',
            name='patient_last_name',
        ),
    ]
